<?php
// $Id: form_overrides.install

/**
* Implementation of hook_install()
*/
function form_overrides_install() {
  // Set the module weight so it can override other modules.
  db_query("UPDATE {system} SET weight = 99 WHERE name = 'form_overrides'");
}

/**
* Implementation of hook_uninstall()
*/
function form_overrides_uninstall() {
  // Remove the module from the system table
  db_query("DELETE FROM {system} WHERE name = 'form_overrides'");
}